### PR TITLE
Add alliance selector

### PR DESCRIPTION
**Pull request by Moeez-Muhammad**
So I tried to add an alliance selector to addMatch.js

It failed.

Please help.

### CODE REVIEW

**Comment by squishybanana04** [comment]
There are a few things that could be wrong here, and my scouting app code isn't the cleanest, but the error most likely is because you didn't update both dataMap.js files. I have this stupid system where one is used for the QR code generation and the other is used for QR code reading. Look at `desktopSide/public/datamap.js`°

**Comment by Moeez-Muhammad** [comment]
I actually didn't notice that, I'll update it However, the immediate error that I got was as soon as I hit the add match button. It was first a bunch of reference and import errors which I fixed by importing dataMap. However, now it's telling me this:
``Unhandled JS Exception: TypeError: undefined is not an object (evaluating 'this.props.data[x.dataNames.alliance[0]]')

**Comment by squishybanana04** [comment]
Look at `onSubmit` on line 141 (I think) and `createMatch` on line 51 in `mainScreen.js`. I didn't notice that you were adding to the create match pop-up. This probably won't fix the error you were given. Was the error on the computer or the app?

**Comment by Moeez-Muhammad** [comment]
On the app. I haven't fiddled with the desktop side yet.

**Comment by squishybanana04** [comment]
OK the I'm starting to see the issue but it's a little complicated to explain on a phone keyboard. Are you free to call? I'm away so I don't have my computer

**Comment by Moeez-Muhammad** [comment]
Welp now we don't need the input. However, if you get the time, it would be beneficial to have documentation on how the stuff works and how to add new things. I can help too since I kinda understand it now.

**Pull request closed without merging**
